version: '3.9'

services:
  chatbot-mariadb:
    image: mariadb:10.8.3
    container_name: chatbot-mariadb-container
    command:
      [
        '--default-time-zone=+00:00',
        '--default-authentication-plugin=mysql_native_password'
      ]
    ports:
      - 3307:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - chatbot-mariadb-data:/var/lib/mysql

  chatbot-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: chatbot-phpmyadmin-container
    environment:
      - PMA_HOST=chatbot-mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root
      - UPLOAD_LIMIT=120M
    ports:
      - "8002:80"
    depends_on:
      - chatbot-mariadb

  chatbot-api:
    depends_on:
        - chatbot-mariadb
    container_name: chatbot-api-container
    build: 
      context: .
      dockerfile: Dockerfile
    command: tail -F /dev/null

volumes:
  chatbot-mariadb-data: